name: Alwan
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.6.2=py312haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h827c3e9_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312haa95532_0
  - attrs=24.3.0=py312haa95532_0
  - babel=2.11.0=py312haa95532_0
  - beautifulsoup4=4.12.3=py312haa95532_0
  - bleach=6.2.0=py312haa95532_0
  - brotli-python=1.0.9=py312h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.12.31=haa95532_0
  - certifi=2024.12.14=py312haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - debugpy=1.8.11=py312h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h8ddb27b_0
  - h11=0.14.0=py312haa95532_0
  - httpcore=1.0.2=py312haa95532_0
  - httpx=0.27.0=py312haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.7=py312haa95532_0
  - ipykernel=6.29.5=py312haa95532_0
  - ipython=8.30.0=py312haa95532_0
  - ipywidgets=8.1.5=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jinja2=3.1.4=py312haa95532_1
  - jpeg=9e=h827c3e9_3
  - json5=0.9.25=py312haa95532_0
  - jsonschema=4.23.0=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jupyter=1.0.0=py312haa95532_9
  - jupyter-lsp=2.2.0=py312haa95532_0
  - jupyter_client=8.6.0=py312haa95532_0
  - jupyter_console=6.6.3=py312haa95532_1
  - jupyter_core=5.7.2=py312haa95532_0
  - jupyter_events=0.10.0=py312haa95532_0
  - jupyter_server=2.14.1=py312haa95532_0
  - jupyter_server_terminals=0.4.4=py312haa95532_1
  - jupyterlab=4.2.5=py312haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312haa95532_0
  - jupyterlab_widgets=3.0.13=py312haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.2=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py312h827c3e9_1
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mistune=2.0.4=py312haa95532_0
  - nbclient=0.8.0=py312haa95532_0
  - nbconvert=7.16.4=py312haa95532_0
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - notebook=7.2.2=py312haa95532_1
  - notebook-shim=0.2.3=py312haa95532_0
  - openssl=3.0.15=h827c3e9_0
  - overrides=7.4.0=py312haa95532_0
  - packaging=24.2=py312haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py312haa95532_0
  - pip=24.2=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - ply=3.11=py312haa95532_1
  - prometheus_client=0.21.0=py312haa95532_0
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h827c3e9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312haa95532_1
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.8=h14ffc60_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.20.0=py312haa95532_0
  - python-json-logger=3.2.1=py312haa95532_0
  - pytz=2024.1=py312haa95532_0
  - pywin32=308=py312h5da7b33_0
  - pywinpty=2.0.14=py312h72d21ff_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - pyzmq=26.2.0=py312h5da7b33_0
  - qt-main=5.15.2=h19c9488_11
  - qtconsole=5.6.0=py312haa95532_0
  - qtpy=2.4.1=py312haa95532_0
  - referencing=0.30.2=py312haa95532_0
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rpds-py=0.22.3=py312h636fa0f_0
  - send2trash=1.8.2=py312haa95532_1
  - setuptools=75.1.0=py312haa95532_0
  - sip=6.7.12=py312h5da7b33_1
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312haa95532_0
  - soupsieve=2.5=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312haa95532_0
  - tinycss2=1.2.1=py312haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - urllib3=2.2.3=py312haa95532_0
  - vc=14.40=haa95532_2
  - vs2015_runtime=14.42.34433=h9531ae6_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - wheel=0.44.0=py312haa95532_0
  - widgetsnbextension=4.0.13=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - adjusttext==1.3.0
      - aiofiles==24.1.0
      - alembic==1.15.1
      - altair==5.5.0
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - backoff==2.2.1
      - bertopic==0.17.0
      - blinker==1.9.0
      - boto3==1.38.46
      - botocore==1.38.46
      - cachetools==5.5.2
      - cffi==2.0.0
      - chardet==5.2.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - comtypes==1.4.11
      - contourpy==1.3.1
      - cryptography==46.0.3
      - cycler==0.12.1
      - dacite==1.6.0
      - dagshub==0.5.10
      - dagshub-annotation-converter==0.1.10
      - databricks-sdk==0.57.0
      - dataclasses-json==0.6.7
      - deprecation==2.1.0
      - distro==1.9.0
      - docker==7.1.0
      - et-xmlfile==2.0.0
      - fastapi==0.115.12
      - ffmpeg-python==0.2.0
      - ffmpy==0.6.0
      - filelock==3.18.0
      - flask==3.1.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozendict==2.4.6
      - fsspec==2025.5.1
      - future==1.0.0
      - gensim==4.3.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.2
      - google-api-python-client==2.170.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - gql==3.5.3
      - gradio==5.34.0
      - gradio-client==1.10.3
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - groovy==0.1.2
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - gspread==6.2.0
      - h2==4.3.0
      - hdbscan==0.8.40
      - hpack==4.1.0
      - httplib2==0.22.0
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - hyperframe==6.1.0
      - imbalanced-learn==0.13.0
      - imblearn==0.0
      - importlib-metadata==8.7.0
      - ipython-autotime==0.3.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyter-http-over-ws==0.0.8
      - kiwisolver==1.4.8
      - langchain==1.0.2
      - langchain-classic==1.0.0
      - langchain-community==0.4
      - langchain-core==1.0.1
      - langchain-openai==1.0.1
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.38
      - lightgbm==4.6.0
      - llvmlite==0.44.0
      - lockfile==0.12.2
      - luigi==3.6.0
      - lxml==5.3.1
      - mako==1.3.9
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - minio==7.2.15
      - mlflow==3.1.1
      - mlflow-skinny==3.1.1
      - mpmath==1.3.0
      - multidict==6.6.2
      - multitasking==0.0.11
      - mypy-extensions==1.1.0
      - narwhals==1.41.0
      - networkx==3.5
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - openai==2.6.1
      - openpyxl==3.1.5
      - opentelemetry-api==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - orjson==3.10.18
      - ormsgpack==1.11.0
      - outcome==1.3.0.post0
      - pandas==2.2.3
      - pandas-datareader==0.10.0
      - pangres==4.2.1
      - pathvalidate==3.3.1
      - patsy==1.0.1
      - peewee==3.17.9
      - pgvector==0.4.1
      - pillow==11.1.0
      - pillow-heif==0.22.0
      - plotly==6.1.2
      - postgrest==2.24.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psycopg2==2.9.10
      - py4j==0.10.9.7
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycryptodome==3.22.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.11.0
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyjwt==2.10.1
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pypdf2==3.0.1
      - pyspark==3.5.5
      - python-daemon==3.1.2
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - rank-bm25==0.2.2
      - realtime==2.24.0
      - regex==2024.11.6
      - reportlab==4.4.1
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rsa==4.9
      - ruff==0.11.13
      - s3transfer==0.13.0
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - selenium==4.27.1
      - semantic-version==2.10.0
      - semver==3.0.4
      - sentence-transformers==5.1.2
      - shap==0.50.0
      - shellingham==1.5.4
      - sklearn-compat==0.1.3
      - slicer==0.0.8
      - smart-open==7.1.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.37
      - sqlparse==0.5.3
      - squarify==0.4.4
      - starlette==0.46.2
      - statsmodels==0.14.4
      - storage3==2.24.0
      - streamlit==1.45.1
      - strenum==0.4.15
      - supabase==2.24.0
      - supabase-auth==2.24.0
      - supabase-functions==2.24.0
      - sympy==1.14.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.57.0.dev0
      - treelib==1.8.0
      - trio==0.28.0
      - trio-websocket==0.11.1
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2024.2
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - uvicorn==0.34.3
      - waitress==3.0.2
      - watchdog==6.0.0
      - webcolors==24.11.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wordcloud==1.9.4
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xgboost==3.0.2
      - xlrd==2.0.1
      - yarl==1.20.1
      - yfinance==0.2.54
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: C:\Users\US3R\anaconda3\envs\Alwan
